[package]
name = "echo-server"
version = "0.1.0"
authors = ["Mika Viljanen <mika.viljanen@wunderdog.fi>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["json"]
